### ISSUE TITLE
Can't toast on a thread that has not called Looper.prepare()

### ISSUE THREAD

**Issue by triplesky** [Dovar66/DovaToast#11]
有没有遇到这个问题

**Comment by triplesky** [comment]
> 有没有遇到这个问题

Can't toast on a thread that has not called Looper.prepare()

...dtoast.inner.SystemToast.showInternal(Unknown Source:13)

**Comment by Dovar66** [comment]
DToast跟原生Toast的使用是一样的，不应该直接在子线程中调用show()方法

**Comment by Likeyong** [comment]
在子线程调用Looper.prepare(); 之后还是不行,请问有解决办法吗
