### ISSUE TITLE
Application级别的context不显示吐司啊 ，而且我用Activity级别的，关闭页面吐司立马就关闭了，有的时候是不想立马关闭的

### ISSUE THREAD

**Issue by 385841539** [Dovar66/DovaToast#12]

**Comment by Dovar66** [comment]
麻烦发一下设备信息

**Comment by 385841539** [comment]
oppo r9，安卓7.1.1

**Comment by Dovar66** [comment]
请问targetSdkVersion是多少

**Comment by 385841539** [comment]
27 哦

**Comment by Dovar66** [comment]
你用demo跑一下，7.1应该不会有问题的。如果demo也有问题，麻烦看下DovaTN.displayToast()是不是抛出了token null is not valid这个异常

**Comment by 385841539** [comment]
我试了 ，按home键 后所有吐司就取消了

**Comment by 385841539** [comment]
应为大部分应用都会有 回到后台的提示嘛 ， 那这样 吐司 基本出来就没了。

**Comment by 385841539** [comment]
我试了 放到我的项目里面 ， 用华为的8.0 系统正常  ， 用 那个oppo 的就会存在报错的情况 ，

**Comment by hui928636443** [comment]
吓得我都不敢用

**Comment by joy-jianqiang** [comment]
> 你用demo跑一下，7.1应该不会有问题的。如果demo也有问题，麻烦看下DovaTN.displayToast()是不是抛出了token null is not valid这个异常

我这边Oppo r11  7.1.1， dialog和applicationContext的确显示不出toast,需要开启权限才行  

DovaTN.displayToast(）异常是
android.view.WindowManager$BadTokenException: Unable to add window -- token null is not valid; is your activity running?
