### ISSUE TITLE
如何给添加的view上的按钮添加点击事件？

### ISSUE THREAD

**Issue by coderfelixby** [Dovar66/DovaToast#16]
如题

**Comment by Dovar66** [comment]
Toast窗口上的View要支持点击事件的话，需要申请悬浮窗权限，否则存在兼容性问题

**Comment by coderfelixby** [comment]
如果用popwindow实现呢？

**Comment by Dovar66** [comment]
> 
> 
> 如果用popwindow实现呢？

popwindow相当于普通的view，要依附于Activity的，跨界面或者应用切后台就不能展示了
