### ISSUE TITLE
vivo手机上不会弹出toast哦

### ISSUE THREAD

**Issue by LinX1874** [Dovar66/DovaToast#17]
vivo手机上不会弹出toast哦

**Comment by Dovar66** [comment]
麻烦提供下具体机型和系统版本，以及log日志

**Comment by georoid2014** [comment]
oppoR11系统Android7.1.1系统，关闭通知的情况下也不显示

**Comment by sinlazhan** [comment]
vivo x23  Android9 关闭通知权限下无法显示

**Comment by thsai** [comment]
请问解决情况如何了

**Comment by zhangjianhd** [comment]
低版本的vivo的rom权限被厂商自己改了，使用谷歌的权限检测总是返回有权限的，问题应该出在这里。vivo、oppo和魅族的低版本的一些rom都有这个问题，不知道厂商怎么想的，适配极度痛苦

**Comment by ZhangJian96** [comment]
瞎改rom,改了又不提供方法去检测。目前看到网上为了适配这几家rom采用比较多的方案是调用某个需要权限的api然后多次的try catch,直到没有异常说明授予权限了

**Comment by Tougee** [comment]
oppo vivo具体有哪些版本权限检测有问题，大家有设备的列出来统计一下？这样就能在这个项目基础上再适配下这些设备了

**Comment by Dovar66** [comment]
> 
> 
> oppo vivo具体有哪些版本权限检测有问题，大家有设备的列出来统计一下？这样就能在这个项目基础上再适配下这些设备了

对的，如果大家能把遇到问题的设备列出来的话更方便适配
