### ISSUE TITLE
布局可以用系统的布局 不然不同手机布局不一致

### ISSUE THREAD

**Issue by Wenlong-Guo** [Dovar66/DovaToast#18]
// toast距离底部边距的dimenId

int yOffsetId = Resources.getSystem().getIdentifier("toast_y_offset", "dimen", "android");

// toast默认布局

int layoutId = Resources.getSystem().getIdentifier("transient_notification", "layout", "android");

**Comment by Dovar66** [comment]
setView()支持修改布局，你可以自行修改
