### ISSUE TITLE
Android 11 警告

### ISSUE THREAD

**Issue by limxing** [Dovar66/DovaToast#20]
`W: Accessing hidden field Landroid/widget/Toast;->mTN:Landroid/widget/Toast$TN; (greylist-max-p, reflection, denied)
W: java.lang.NoSuchFieldException: No field mTN in class Landroid/widget/Toast; (declaration of 'android.widget.Toast' appears in /system/framework/framework.jar!classes3.dex)
W:     at java.lang.Class.getDeclaredField(Native Method)
W:     at com.dovar.dtoast.inner.SystemToast.getField(SystemToast.java:235)
W:     at com.dovar.dtoast.inner.SystemToast.setupToastAnim(SystemToast.java:215)
W:     at com.dovar.dtoast.inner.SystemToast.showInternal(SystemToast.java:82)
W:     at com.dovar.dtoast.inner.SystemTN.displayToast(SystemTN.java:131)
W:     at com.dovar.dtoast.inner.SystemTN.showNextToast(SystemTN.java:111)
W:     at com.dovar.dtoast.inner.SystemTN.notifyNewToastComeIn(SystemTN.java:71)
W:     at com.dovar.dtoast.inner.SystemTN.add(SystemTN.java:40)
W:     at com.dovar.dtoast.inner.SystemToast.show(SystemToast.java:52)
`

**Comment by Dovar66** [comment]
DToast只在API26以下才会反射访问mTN：
    Field sField_TN = Toast.class.getDeclaredField("mTN")
具体代码可以clone后查看SystemToast#hookHandler()

**Comment by limxing** [comment]
SystemToast#setupToastAnim 并没有判断

**Comment by Dovar66** [comment]
> SystemToast#setupToastAnim 并没有判断

感谢提醒，我补充处理一下
