### ISSUE TITLE
频繁弹 DToast 的情况下，土司无法显示

### ISSUE THREAD

**Issue by louisgeek** [Dovar66/DovaToast#23]
场景：较频繁地弹 DToast 的情况
步骤：第一步自行弹出一个系统的 Toast，然后马上一直频繁弹 DToast
结果：DToast 一直弹不出来，如果接下来控制一下停止弹 DToast，过会再继续弹，那么现在就能够弹出【换句话说，如果有个需求是频繁弹 DToast 的情况是紧接着一个系统的 Toast 后面的时候，那么 DToast 无法弹出】
机型：
三星Galaxy S10
samsung SM-G9730  
Android 11 
One UI 3.1 
说明：
代码调试走的是 SystemTN
com.dovar.dtoast.inner.SystemTN#displayToast

**Comment by Dovar66** [comment]
在系统Toast后接DToast时，第一个DToast的展示受系统Toast队列逻辑控制
