### ISSUE TITLE
huawei  android 8.1

### ISSUE THREAD

**Issue by nshzzu130** [Dovar66/DovaToast#5]
![image](https://user-images.githubusercontent.com/19965970/50534132-54997b00-0b73-11e9-8061-0a4705065993.png)

**Comment by Dovar66** [comment]
收到，这两天我修复一下

**Comment by Dovar66** [comment]
已修复，请查看Release1.1.2，麻烦帮忙验证一下，如果还有问题请加我QQ847736308
