### ISSUE TITLE
360手机toast不显示

### ISSUE THREAD

**Issue by protectedMan** [Dovar66/DovaToast#6]
手机Android版本25，
app targetsdk 28
关闭权限后，两种方式均不可正常弹出
 UIUtils.showToast(this, "请填写手机号"); 不可以弹出
 UIUtils.showToast(CSApp.getApplication(), "请填写手机号"); 不可以弹出

**Comment by Dovar66** [comment]
麻烦提供更多调试信息，发一下DovaTN类中try-catch的异常的截图

**Comment by protectedMan** [comment]
W/WindowManager: Attempted to add a toast window with bad token null.  
只有这一条信息

**Comment by Dovar66** [comment]
麻烦加我QQ847736308

**Comment by Dovar66** [comment]
机型：360 1707-A01
问题分析：使用DovaToast时，调用windowManager.addView()失败，且addView方法没有将BadTokenException异常抛出，正常失败应该抛出异常
意外发现：360的这个机型关闭通知权限并不会导致系统Toast无法弹出，与MIUI类似。
解决方案：暂时将该机型加入白名单，在该机型上直接使用SystemToast，近期将提交更新代码，代码提交后我会关闭这个issue

待验证：需要更多360机型验证以下两点，1.是否所有360rom的通知权限都不会影响Toast弹出
2.是否所有360rom的windowManager.addView()失败时都不会抛出异常

**Comment by protectedMan** [comment]
这个问题解决了吗
