### ISSUE TITLE
努比亚8.1系统，关闭通知权限DToast不显示

### ISSUE THREAD

**Issue by xuxh6** [Dovar66/DovaToast#9]
努比亚8.1系统，关闭通知权限DToast不显示

**Comment by Dovar66** [comment]
能否贴下日志，我这里没有努比亚手机

**Comment by xuxh6** [comment]
> 能否贴下日志，我这里没有努比亚手机

E/SchedPolicy: set_timerslack_ns write failed: Operation not permitted

**Comment by Dovar66** [comment]
> 
> 
> > 能否贴下日志，我这里没有努比亚手机
> 
> E/SchedPolicy: set_timerslack_ns write failed: Operation not permitted

要WindowManager相关的日志。或者加我QQ847736308

**Comment by Dovar66** [comment]
关闭理由：长时间未提供有效的错误信息

如果仍有问题请联系上方QQ
